const mongoose = require("mongoose");

/**
 * Post Schema
 * Stores blog articles with real view counts and auto-generated timestamps.
 * 
 * Fields:
 *   title       - Article title
 *   excerpt     - Short description for cards
 *   category    - Category name (e.g. "Science", "Philosophy")
 *   image       - Main card image URL
 *   readTime    - Read time string (e.g. "6 min read")
 *   images      - Array of inline detail image URLs
 *   content     - Array of HTML paragraph strings (legacy format)
 *   contentBlocks - Array of content block objects (new format: {type, value})
 *   views       - Real view count, incremented on each detail page visit
 *   tags        - Array of tag strings
 *   status      - "draft" or "published"
 *   isEditorsPick   - Boolean for Editor's Pick section
 *   isTrending      - Boolean for Trending Now section
 *   isFreshPerspective - Boolean for Fresh Perspectives section
 *   createdAt   - Auto-generated by Mongoose timestamps
 *   updatedAt   - Auto-generated by Mongoose timestamps
 */
const postSchema = new mongoose.Schema(
  {
    numericId: {
      type: Number,
      required: [true, "Numeric ID is required"],
      unique: true,
      index: true,
    },
    title: {
      type: String,
      required: [true, "Title is required"],
      trim: true,
    },
    excerpt: {
      type: String,
      required: [true, "Excerpt is required"],
      trim: true,
    },
    category: {
      type: String,
      required: [true, "Category is required"],
      trim: true,
    },
    image: {
      type: String,
      required: [true, "Image URL is required"],
    },
    readTime: {
      type: String,
      required: [true, "Read time is required"],
    },
    images: {
      type: [String],
      default: [],
    },
    content: {
      type: [String],
      default: [],
    },
    contentBlocks: {
      type: [mongoose.Schema.Types.Mixed],
      default: [],
    },
    views: {
      type: Number,
      default: 0,
    },
    tags: {
      type: [String],
      default: [],
    },
    status: {
      type: String,
      enum: ["draft", "published"],
      default: "draft",
    },
    isEditorsPick: {
      type: Boolean,
      default: false,
    },
    isTrending: {
      type: Boolean,
      default: false,
    },
    isFreshPerspective: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Post", postSchema);